import React, { useEffect, useMemo, useState } from 'react'
import api from '../../services/api'
import './StudentAssessments.css'

const stages = [
  ['ANAMNESIS', 'Anamnese', 'Histórico de saúde, rotina e objetivos'], ['BODY', 'Avaliação Corporal', 'Medidas para acompanhar sua evolução'],
  ['POSTURAL', 'Avaliação Postural', 'Fotos privadas em quatro ângulos'], ['STRENGTH', 'Teste de Força', 'Estimativa de 1RM pela fórmula de Epley'],
  ['ENDURANCE', 'Resistência de Força', 'VAM, flexões, prancha e abdominal']
]
const exercises = [['smithSquat', 'Agachamento no Smith'], ['closeGripPulldown', 'Puxador Fechado'], ['seatedDumbbellPress', 'Desenvolvimento com Halteres Sentado'], ['deadlift', 'Levantamento Terra']]
const views = [['FRONT', 'Frente'], ['BACK', 'Costas'], ['RIGHT', 'Lado direito'], ['LEFT', 'Lado esquerdo']]
const statusLabel = { PENDING: 'Pendente', IN_PROGRESS: 'Em andamento', COMPLETED: 'Concluída' }

function Video({ url }) {
  if (!url) return <p className="assessment-video-empty">O vídeo de orientação será disponibilizado em breve.</p>
  const id = url.match(/(?:youtu\.be\/|v=|embed\/)([\w-]{11})/)?.[1]
  return id ? <div className="assessment-video"><iframe src={`https://www.youtube-nocookie.com/embed/${id}`} title="Orientação da Bruna" allowFullScreen /></div> : null
}

export default function StudentAssessments() {
  const [payload, setPayload] = useState({ cycles: [], videos: [] }); const [selected, setSelected] = useState(0); const [open, setOpen] = useState('ANAMNESIS'); const [form, setForm] = useState({}); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  const load = async () => { const { data } = await api.get('/assessments'); setPayload(data); setSelected(Math.max(0, data.cycles.length - 1)) }
  useEffect(() => { load().catch(() => setMessage('Não foi possível carregar sua avaliação.')) }, [])
  const cycle = payload.cycles[selected]
  const videos = useMemo(() => Object.fromEntries(payload.videos.map((item) => [item.stage, item.youtubeUrl])), [payload.videos])
  useEffect(() => { if (cycle) setForm({ ANAMNESIS: cycle.anamnesis || {}, BODY: cycle.bodyAssessment || {}, STRENGTH: cycle.strengthTest || {}, ENDURANCE: cycle.enduranceTest || {}, healthConsent: Boolean(cycle.healthConsentAt) }) }, [cycle?.id])
  const setField = (stage, key, value) => setForm((old) => ({ ...old, [stage]: { ...(old[stage] || {}), [key]: value } }))
  async function save(stage, complete) { try { setBusy(true); const { data } = await api.patch(`/assessments/${cycle.id}/stages/${stage}`, { data: form[stage], complete, healthConsent: form.healthConsent }); setPayload((old) => ({ ...old, cycles: old.cycles.map((item) => item.id === data.id ? data : item) })); setMessage(complete ? 'Etapa concluída.' : 'Rascunho salvo.') } catch (error) { setMessage(error.response?.data?.error || 'Não foi possível salvar.') } finally { setBusy(false) } }
  async function photo(view, file) { if (!file) return; const body = new FormData(); body.append('photo', file); try { setBusy(true); await api.post(`/assessments/${cycle.id}/photos/${view}`, body); await load(); setMessage('Foto enviada com segurança.') } catch (error) { setMessage(error.response?.data?.error || 'Não foi possível enviar a foto.') } finally { setBusy(false) } }
  if (!cycle) return <div className="assessment-state">Carregando avaliação...</div>
  return <section className="assessments-page">
    <header className="assessment-hero"><div><span>Minha evolução</span><h2>{cycle.sequence ? `Reavaliação ${cycle.sequence}` : 'Avaliação inicial'}</h2><p>Faça as etapas na ordem que preferir. O prazo único é de 7 dias corridos.</p></div><div className="assessment-deadline"><strong>{cycle.progress}%</strong><span>{cycle.status === 'COMPLETED' ? 'Concluída' : `${cycle.daysRemaining} dias restantes`}</span></div></header>
    {payload.cycles.length > 1 && <div className="cycle-tabs">{payload.cycles.map((item, index) => <button className={index === selected ? 'active' : ''} onClick={() => setSelected(index)} key={item.id}>{item.sequence ? `Reavaliação ${item.sequence}` : 'Inicial'}</button>)}</div>}
    {message && <div className="assessment-message">{message}</div>}
    <div className="assessment-layout"><nav className="stage-list">{stages.map(([key, title, description]) => <button key={key} className={open === key ? 'active' : ''} onClick={() => setOpen(key)}><span className={`stage-dot ${cycle.stageStatuses[key]?.toLowerCase()}`}>✓</span><span><strong>{title}</strong><small>{description}</small></span><em>{statusLabel[cycle.stageStatuses[key]]}</em></button>)}</nav>
      <article className="stage-panel"><div className="stage-heading"><div><span>Orientação</span><h3>{stages.find(([key]) => key === open)?.[1]}</h3></div><span className="stage-status">{statusLabel[cycle.stageStatuses[open]]}</span></div><Video url={videos[open]} />
        {open === 'ANAMNESIS' && <Anamnesis data={form.ANAMNESIS || {}} set={(k, v) => setField('ANAMNESIS', k, v)} consent={form.healthConsent} setConsent={(v) => setForm((old) => ({ ...old, healthConsent: v }))} />}
        {open === 'BODY' && <Body data={form.BODY || {}} set={(k, v) => setField('BODY', k, v)} />}
        {open === 'STRENGTH' && <Strength data={form.STRENGTH || {}} set={(key, field, value) => setField('STRENGTH', key, { ...(form.STRENGTH?.[key] || {}), [field]: value })} />}
        {open === 'ENDURANCE' && <Endurance data={form.ENDURANCE || {}} set={(k, v) => setField('ENDURANCE', k, v)} />}
        {open === 'POSTURAL' && <div><div className="privacy-note"><strong>Suas fotos são privadas.</strong><p>O envio permite somente a avaliação profissional. Não autoriza publicação, divulgação ou compartilhamento.</p></div><div className="photo-grid">{views.map(([key, label]) => { const existing = cycle.photos.find((item) => item.view === key); return <label key={key}><strong>{label}</strong><span>{existing ? 'Foto recebida · trocar' : 'Selecionar foto'}</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => photo(key, e.target.files[0])} /></label> })}</div></div>}
        {open !== 'POSTURAL' && cycle.status !== 'COMPLETED' && !cycle.expired && <div className="stage-actions"><button disabled={busy} onClick={() => save(open, false)}>Salvar rascunho</button><button className="primary" disabled={busy} onClick={() => save(open, true)}>Concluir etapa</button></div>}
      </article></div>
  </section>
}

function Field({ label, children }) { return <label className="form-field"><span>{label}</span>{children}</label> }
function YesNo({ value, onChange }) { return <select value={value || ''} onChange={(e) => onChange(e.target.value)}><option value="">Selecione</option><option value="NO">Não</option><option value="YES">Sim</option></select> }
function Anamnesis({ data, set, consent, setConsent }) { return <div className="assessment-form"><p className="form-intro">Informe apenas o necessário para a prescrição segura do treino.</p><Field label="Histórico de saúde relevante"><textarea value={data.healthHistory || ''} onChange={(e) => set('healthHistory', e.target.value)} /></Field>{[['injuries','Lesões','injuryDetails'],['pain','Dores atuais','painDetails'],['surgeries','Cirurgias','surgeryDetails'],['medications','Medicamentos em uso','medicationDetails'],['restrictions','Restrições médicas','restrictionDetails']].map(([key,label,details]) => <React.Fragment key={key}><Field label={label}><YesNo value={data[key]} onChange={(v) => set(key,v)} /></Field>{data[key] === 'YES' && <Field label={`Detalhes — ${label.toLowerCase()}`}><textarea value={data[details] || ''} onChange={(e) => set(details,e.target.value)} /></Field>}</React.Fragment>)}<Field label="Rotina diária"><textarea value={data.routine || ''} onChange={(e) => set('routine',e.target.value)} /></Field><div className="form-grid"><Field label="Horas de sono"><input type="number" value={data.sleepHours ?? ''} onChange={(e) => set('sleepHours',e.target.value)} /></Field><Field label="Qualidade do sono"><select value={data.sleepQuality || ''} onChange={(e) => set('sleepQuality',e.target.value)}><option value="">Selecione</option><option>Boa</option><option>Regular</option><option>Ruim</option></select></Field><Field label="Atividade física atual"><input value={data.activityLevel || ''} onChange={(e) => set('activityLevel',e.target.value)} /></Field><Field label="Frequência semanal"><input type="number" value={data.weeklyFrequency ?? ''} onChange={(e) => set('weeklyFrequency',e.target.value)} /></Field></div><Field label="Experiência com treino"><textarea value={data.trainingExperience || ''} onChange={(e) => set('trainingExperience',e.target.value)} /></Field><Field label="Objetivos"><textarea value={data.goals || ''} onChange={(e) => set('goals',e.target.value)} /></Field><label className="consent"><input type="checkbox" checked={Boolean(consent)} onChange={(e) => setConsent(e.target.checked)} /><span>Concordo com o tratamento destes dados sensíveis exclusivamente para avaliação e prescrição do meu treinamento, conforme a Política de Privacidade.</span></label></div> }
function Body({ data, set }) { const fields=[['weightKg','Peso (kg)'],['heightCm','Altura (cm)'],['waistCm','Cintura (cm)'],['hipCm','Quadril (cm)'],['rightArmCm','Braço direito (cm)'],['leftArmCm','Braço esquerdo (cm)'],['rightThighCm','Coxa direita (cm)'],['leftThighCm','Coxa esquerda (cm)']]; return <div className="assessment-form form-grid">{fields.map(([key,label]) => <Field key={key} label={label}><input type="number" step="0.1" value={data[key] ?? ''} onChange={(e) => set(key,e.target.value)} /></Field>)}</div> }
function Strength({ data, set }) { return <div className="exercise-grid">{exercises.map(([key,label]) => { const item=data[key]||{}; const estimate=item.loadKg&&item.repetitions ? (Number(item.loadKg)*(1+Number(item.repetitions)/30)).toFixed(1) : '—'; return <div className="exercise-card" key={key}><strong>{label}</strong><div className="form-grid"><Field label="Carga (kg)"><input type="number" step="0.5" value={item.loadKg ?? ''} onChange={(e) => set(key,'loadKg',e.target.value)} /></Field><Field label="Repetições"><input type="number" value={item.repetitions ?? ''} onChange={(e) => set(key,'repetitions',e.target.value)} /></Field></div><span>1RM estimado <b>{estimate} kg</b></span></div>})}</div> }
function Endurance({ data, set }) { const vam=data.distanceMeters ? (Number(data.distanceMeters)/83.33).toFixed(2) : '—'; return <div className="assessment-form form-grid"><Field label="Modalidade VAM (5 min)"><select value={data.modality || ''} onChange={(e) => set('modality',e.target.value)}><option value="">Selecione</option><option value="BIKE">Bike</option><option value="TREADMILL">Esteira</option></select></Field><Field label="Distância (metros)"><input type="number" value={data.distanceMeters ?? ''} onChange={(e) => set('distanceMeters',e.target.value)} /><small>VAM: {vam} km/h</small></Field><Field label="Flexões até a falha"><input type="number" value={data.pushUps ?? ''} onChange={(e) => set('pushUps',e.target.value)} /></Field><Field label="Prancha até a falha (segundos)"><input type="number" value={data.plankSeconds ?? ''} onChange={(e) => set('plankSeconds',e.target.value)} /></Field><Field label="Abdominal em 1 minuto"><input type="number" value={data.abdominalReps ?? ''} onChange={(e) => set('abdominalReps',e.target.value)} /></Field></div> }
