import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import api from '../services/api'

const labels={weightKg:'Peso (kg)',heightCm:'Altura (cm)',waistCm:'Cintura (cm)',hipCm:'Quadril (cm)',rightArmCm:'Braço direito (cm)',leftArmCm:'Braço esquerdo (cm)',rightThighCm:'Coxa direita (cm)',leftThighCm:'Coxa esquerda (cm)',smithSquat:'Agachamento no Smith',closeGripPulldown:'Puxador Fechado',seatedDumbbellPress:'Desenvolvimento sentado',deadlift:'Levantamento Terra'}
const anamnesisLabels={healthHistory:'Histórico de saúde',injuries:'Lesões',injuryDetails:'Detalhes das lesões',pain:'Dores atuais',painDetails:'Detalhes das dores',surgeries:'Cirurgias',surgeryDetails:'Detalhes das cirurgias',medications:'Medicamentos em uso',medicationDetails:'Detalhes dos medicamentos',restrictions:'Restrições médicas',restrictionDetails:'Detalhes das restrições',routine:'Rotina diária',sleepHours:'Horas de sono',sleepQuality:'Qualidade do sono',activityLevel:'Nível de atividade física',trainingExperience:'Experiência com treino',weeklyFrequency:'Frequência semanal',goals:'Objetivos',relevantNotes:'Observações relevantes'}
const stageLabels={ANAMNESIS:'Anamnese dissertativa',BODY:'Avaliação antropométrica',POSTURAL:'Avaliação postural',STRENGTH:'Teste de força',ENDURANCE:'Teste físico'}
const statusLabels={PENDING:'Pendente',IN_PROGRESS:'Em andamento',COMPLETED:'Concluída'}
const valueLabels={YES:'Sim',NO:'Não',BIKE:'Bicicleta',TREADMILL:'Esteira'}
const safe=(value)=>value===null||value===undefined||value===''?'-':String(valueLabels[value]||value).replace(/[^\x20-\x7E\xA0-\xFF]/g,'')
const wrap=(text,max=88)=>{const lines=[];let line='';for(const word of safe(text).split(/\s+/)){if(`${line} ${word}`.trim().length>max){lines.push(line);line=word}else line=`${line} ${word}`.trim()}if(line)lines.push(line);return lines}
const embedPhoto=async(pdf,response,mime)=>{let bytes=new Uint8Array(response.data);if(mime==='image/png')return pdf.embedPng(bytes);if(mime==='image/jpeg')return pdf.embedJpg(bytes);const bitmap=await createImageBitmap(new Blob([bytes],{type:mime})),canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;canvas.getContext('2d').drawImage(bitmap,0,0);const converted=await new Promise((resolve)=>canvas.toBlob(resolve,'image/png'));bytes=new Uint8Array(await converted.arrayBuffer());return pdf.embedPng(bytes)}

export async function generateAssessmentPdf({cycle,previous,student,settings,professional=false}){
  const pdf=await PDFDocument.create(),regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);let page,y
  const addPage=()=>{page=pdf.addPage([595.28,841.89]);page.drawRectangle({x:0,y:765,width:595.28,height:77,color:rgb(.09,.15,.28)});page.drawText('BRUNA AFFONSO',{x:44,y:807,size:17,font:bold,color:rgb(1,1,1)});page.drawText(professional?'Relatório profissional de avaliação':'Meu relatório de evolução',{x:44,y:789,size:9,font:regular,color:rgb(.86,.89,1)});y=740};addPage()
  const ensure=(height=18)=>{if(y-height<45)addPage()}
  const title=(text)=>{ensure(28);page.drawText(safe(text),{x:44,y,size:13,font:bold,color:rgb(.15,.23,.42)});y-=22}
  const row=(label,value)=>{const lines=wrap(`${label}: ${safe(value)}`);ensure(lines.length*13+4);lines.forEach((line,index)=>page.drawText(line,{x:50,y:y-index*13,size:9,font:regular,color:rgb(.12,.16,.25)}));y-=lines.length*13+3}
  const photosSection=async(photos,heading)=>{if(!photos?.length)return;title(heading);for(const photo of photos){ensure(190);try{const response=await api.get(photo.url,{responseType:'arraybuffer'}),image=await embedPhoto(pdf,response,photo.mimeType),dimensions=image.scaleToFit(170,170);page.drawImage(image,{x:50,y:y-dimensions.height,width:dimensions.width,height:dimensions.height});page.drawText(safe(photo.view),{x:50,y:y-dimensions.height-12,size:8,font:regular,color:rgb(.44,.48,.55)});y-=dimensions.height+25}catch(error){row(`Foto ${photo.view}`,'Imagem privada indisponivel')}}}
  page.drawText(cycle.sequence?`Reavaliação ${cycle.sequence}`:'Avaliação inicial',{x:44,y,size:19,font:bold,color:rgb(.09,.13,.23)});y-=24;row('Aluna',student?.name||'Aluna');row('Início',new Date(cycle.startedAt||cycle.createdAt).toLocaleDateString('pt-BR'));row('Prazo',new Date(cycle.deadlineAt).toLocaleDateString('pt-BR'));row('Conclusão',cycle.completedAt?new Date(cycle.completedAt).toLocaleDateString('pt-BR'):'Em andamento');row('Progresso',`${cycle.progress}%`);Object.entries(cycle.stageStatuses||{}).forEach(([stage,status])=>row(stageLabels[stage]||stage,statusLabels[status]||status))
  title('Medidas corporais');Object.entries(labels).filter(([key])=>cycle.bodyAssessment&&key in cycle.bodyAssessment).forEach(([key,label])=>row(label,cycle.bodyAssessment[key]))
  title('Teste de força - fórmula de Epley');Object.entries(cycle.strengthTest||{}).forEach(([key,item])=>row(labels[key]||key,`${safe(item.loadKg)} kg x ${safe(item.repetitions)} repetições | 1RM ${safe(item.estimatedOneRm)} kg`))
  title('Teste físico');row('Modalidade VAM (5 min)',cycle.enduranceTest?.modality);row('Distância em 5 minutos',`${safe(cycle.enduranceTest?.distanceMeters)} m`);row('VAM calculada',`${safe(cycle.enduranceTest?.vamKmh)} km/h`);row('Flexões até a falha',cycle.enduranceTest?.pushUps);row('Prancha até a falha',`${safe(cycle.enduranceTest?.plankSeconds)} segundos`);row('Abdominal em 1 minuto',cycle.enduranceTest?.abdominalReps)
  if(previous){title('Comparativo com o ciclo anterior');Object.entries(labels).filter(([key])=>cycle.bodyAssessment&&key in cycle.bodyAssessment).forEach(([key,label])=>row(label,`${safe(previous.bodyAssessment?.[key])} -> ${safe(cycle.bodyAssessment?.[key])}`));Object.entries(cycle.strengthTest||{}).forEach(([key,item])=>row(`1RM ${labels[key]||key}`,`${safe(previous.strengthTest?.[key]?.estimatedOneRm)} -> ${safe(item.estimatedOneRm)} kg`));[['vamKmh','VAM (km/h)'],['pushUps','Flexões'],['plankSeconds','Prancha (s)'],['abdominalReps','Abdominal']].forEach(([key,label])=>row(label,`${safe(previous.enduranceTest?.[key])} -> ${safe(cycle.enduranceTest?.[key])}`))}
  if(cycle.anamnesis){title(professional?'Anamnese - acesso profissional':'Minha anamnese');Object.entries(cycle.anamnesis).forEach(([key,value])=>{if(value!==''&&value!==null)row(anamnesisLabels[key]||key,value)})}
  if(previous)await photosSection(previous.photos,'Fotos anteriores - comparação')
  await photosSection(cycle.photos,cycle.sequence?'Fotos atuais - reavaliação':'Fotos da avaliação postural')
  if(settings?.logo?.startsWith?.('data:image/')){try{const bytes=Uint8Array.from(atob(settings.logo.split(',')[1]),character=>character.charCodeAt(0)),logo=settings.logo.includes('png')?await pdf.embedPng(bytes):await pdf.embedJpg(bytes),dimensions=logo.scaleToFit(112,42);for(const item of pdf.getPages()){const frameX=431,frameY=782;item.drawRectangle({x:frameX,y:frameY,width:120,height:48,color:rgb(1,1,1)});item.drawImage(logo,{x:frameX+(120-dimensions.width)/2,y:frameY+(48-dimensions.height)/2,width:dimensions.width,height:dimensions.height})}}catch(error){}}
  const pages=pdf.getPages();pages.forEach((item,index)=>item.drawText(`Documento privado - página ${index+1} de ${pages.length}`,{x:44,y:24,size:8,font:regular,color:rgb(.44,.48,.55)}))
  const bytes=await pdf.save(),blob=new Blob([bytes],{type:'application/pdf'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${cycle.sequence?`reavaliacao-${cycle.sequence}`:'avaliacao-inicial'}-${safe(student?.name||'aluna').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-')}.pdf`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)
}
