import React, { useEffect, useMemo, useState } from 'react'
import api from '../../services/api'
import './AdminAssessments.css'

const stageNames={ANAMNESIS:'Anamnese',BODY:'Avaliação corporal',POSTURAL:'Avaliação postural',STRENGTH:'Teste de força',ENDURANCE:'Resistência'}
const exercises={smithSquat:'Agachamento no Smith',closeGripPulldown:'Puxador Fechado',seatedDumbbellPress:'Desenvolvimento sentado',deadlift:'Levantamento Terra'}
function PrivateImage({ photo }) { const [src,setSrc]=useState(''); useEffect(()=>{let url;api.get(photo.url,{responseType:'blob'}).then(({data})=>{url=URL.createObjectURL(data);setSrc(url)});return()=>url&&URL.revokeObjectURL(url)},[photo.id]); return src?<img src={src} alt={photo.view}/>:<span>Carregando foto…</span> }
const delta=(current,previous,key,suffix='')=>{const a=Number(current?.[key]);const b=Number(previous?.[key]);if(!Number.isFinite(a)||!Number.isFinite(b))return '—';const d=a-b;return `${d>0?'+':''}${d.toFixed(1)}${suffix}`}

export default function AdminAssessments(){
 const [students,setStudents]=useState([]),[studentId,setStudentId]=useState(''),[data,setData]=useState(null),[videos,setVideos]=useState({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{Promise.all([api.get('/admin/students'),api.get('/admin/assessment-videos')]).then(([s,v])=>{const approved=s.data.filter(x=>x.studentId&&x.status==='APPROVED');setStudents(approved);if(approved[0])setStudentId(approved[0].studentId);setVideos(Object.fromEntries(v.data.map(x=>[x.stage,x.youtubeUrl||''])))}).catch(()=>setMessage('Não foi possível carregar as avaliações.'))},[])
 useEffect(()=>{if(studentId)api.get(`/admin/students/${studentId}/assessments`).then(({data})=>setData(data)).catch(()=>setData({cycles:[]}))},[studentId])
 async function release(){try{setBusy(true);await api.post(`/admin/students/${studentId}/reassessments`);const response=await api.get(`/admin/students/${studentId}/assessments`);setData(response.data);setMessage('Nova reavaliação liberada por 7 dias.')}catch(e){setMessage(e.response?.data?.error||'Não foi possível liberar.')}finally{setBusy(false)}}
 async function saveVideos(){try{setBusy(true);await api.put('/admin/assessment-videos',{videos});setMessage('Vídeos atualizados.')}catch(e){setMessage(e.response?.data?.error||'Revise os links informados.')}finally{setBusy(false)}}
 const latest=data?.cycles?.at(-1),previous=data?.cycles?.at(-2)
 return <section className="admin-assessments"><header><div><span className="admin-eyebrow">Acompanhamento individual</span><h2>Avaliações e reavaliações</h2><p>Consulte dados privados, evolução e libere um novo ciclo somente quando fizer sentido para a aluna.</p></div><button disabled={!studentId||busy} onClick={release}>Liberar reavaliação</button></header>{message&&<div className="aa-message">{message}</div>}
 <div className="aa-grid"><aside><h3>Alunas</h3>{students.map(s=><button className={studentId===s.studentId?'active':''} onClick={()=>setStudentId(s.studentId)} key={s.studentId}><strong>{s.name}</strong><span>{s.email}</span></button>)}</aside><main>{!data?<p>Selecione uma aluna.</p>:<><div className="aa-cycles">{data.cycles.map(c=><article key={c.id}><span>{c.sequence?`Reavaliação ${c.sequence}`:'Inicial'}</span><strong>{c.progress}%</strong><small>{c.status==='COMPLETED'?'Concluída':`${c.daysRemaining} dias restantes`}</small><div className="mini-progress"><i style={{width:`${c.progress}%`}}/></div></article>)}</div>{latest&&<Cycle cycle={latest}/>} {latest&&previous&&<Comparison current={latest} previous={previous}/>}</>}</main></div>
 <section className="aa-videos"><div><h3>Vídeos por etapa</h3><p>Links do YouTube exibidos dentro de cada tópico.</p></div><div className="aa-video-fields">{Object.entries(stageNames).map(([key,label])=><label key={key}><span>{label}</span><input placeholder="https://youtube.com/watch?v=…" value={videos[key]||''} onChange={e=>setVideos(v=>({...v,[key]:e.target.value}))}/></label>)}</div><button disabled={busy} onClick={saveVideos}>Salvar vídeos</button></section>
 </section>
}
function Cycle({cycle}){return <section className="aa-detail"><h3>{cycle.sequence?`Reavaliação ${cycle.sequence}`:'Avaliação inicial'} — respostas atuais</h3><div className="aa-statuses">{Object.entries(cycle.stageStatuses).map(([k,v])=><span key={k}><b>{stageNames[k]}</b>{v==='COMPLETED'?'Concluída':v==='IN_PROGRESS'?'Em andamento':'Pendente'}</span>)}</div>{cycle.anamnesis&&<details><summary>Anamnese (dados sensíveis)</summary><pre>{JSON.stringify(cycle.anamnesis,null,2)}</pre></details>}<Data title="Medidas corporais" data={cycle.bodyAssessment}/><Data title="Teste de força" data={cycle.strengthTest}/><Data title="Resistência" data={cycle.enduranceTest}/>{cycle.photos.length>0&&<div><h4>Fotos posturais privadas</h4><div className="aa-photos">{cycle.photos.map(p=><figure key={p.id}><PrivateImage photo={p}/><figcaption>{p.view}</figcaption></figure>)}</div></div>}</section>}
function Data({title,data}){if(!data)return null;return <details><summary>{title}</summary><pre>{JSON.stringify(data,null,2)}</pre></details>}
function Comparison({current,previous}){const bodyKeys={weightKg:'Peso',waistCm:'Cintura',hipCm:'Quadril',rightArmCm:'Braço direito',leftArmCm:'Braço esquerdo',rightThighCm:'Coxa direita',leftThighCm:'Coxa esquerda'};return <section className="aa-comparison"><h3>Comparativo automático</h3><div className="comparison-table">{Object.entries(bodyKeys).map(([k,label])=><div key={k}><span>{label}</span><b>{previous.bodyAssessment?.[k]??'—'} → {current.bodyAssessment?.[k]??'—'}</b><em>{delta(current.bodyAssessment,previous.bodyAssessment,k,' cm')}</em></div>)}{Object.entries(exercises).map(([k,label])=><div key={k}><span>1RM · {label}</span><b>{previous.strengthTest?.[k]?.estimatedOneRm??'—'} → {current.strengthTest?.[k]?.estimatedOneRm??'—'}</b><em>{delta(current.strengthTest?.[k],previous.strengthTest?.[k],'estimatedOneRm',' kg')}</em></div>)}{[['vamKmh','VAM'],['pushUps','Flexões'],['plankSeconds','Prancha'],['abdominalReps','Abdominal']].map(([k,label])=><div key={k}><span>{label}</span><b>{previous.enduranceTest?.[k]??'—'} → {current.enduranceTest?.[k]??'—'}</b><em>{delta(current.enduranceTest,previous.enduranceTest,k)}</em></div>)}</div><PhotoComparison current={current} previous={previous}/></section>}
function PhotoComparison({current,previous}){const pairs=useMemo(()=>current.photos.map(photo=>[previous.photos.find(p=>p.view===photo.view),photo]).filter(([a])=>a),[current,previous]);if(!pairs.length)return null;return <div><h4>Antes × depois</h4><div className="aa-photo-compare">{pairs.map(([before,after])=><div key={after.view}><figure><PrivateImage photo={before}/><figcaption>Antes</figcaption></figure><figure><PrivateImage photo={after}/><figcaption>Atual</figcaption></figure></div>)}</div></div>}
